### ISSUE TITLE
Unable to install theme from git

### ISSUE THREAD

**Issue by petermakowski** [canonical/discourse-k8s-operator#135] opened 2023-10-31 09:46 UTC
### Bug Description

It doesn’t seem currently possible to install themes from git due to 500 errors.

### To Reproduce

1. Go to [MAAS Discourse](https://discourse.maas.io/) admin panel.
2. Navigate to [Customize > Themes](https://discourse.maas.io/admin/customize/themes).
3. Click the "Install" button.
4. Select "From a Git repository" and paste https://github.com/canonical/maas-discourse-theme.
5. Click "Install".

### Environment

https://discourse.maas.io/

### Relevant log output

```shell
https://discourse.maas.io/admin/themes/import

Request Method:

POST

Status Code:

500 Internal Server Error
```

### Additional context

![image](https://github.com/canonical/discourse-k8s-operator/assets/7452681/f5274d93-d87b-4a8e-a088-2fb223beb6a1)

The same error happens when installing a stock theme (which should exclude this being caused by any issues with our maas discourse theme) https://github.com/discourse/material-design-stock-theme

**Comment by tmerten** [comment] 2023-11-01 08:24
FYI: I think the instance does not have access to the web in general. I noticed timeout errors for version checks in the logs as well.

**Comment by merkata** [comment] 2024-03-22 12:01
We will have a look at this, I know right now we're bundling plugins in the container, though for themes you should be able to install them and that should have to be a networking issue. Will post an update.
FYI @Thanhphan1147 @nrobinaubertin

**Comment by Thanhphan1147** [comment] 2024-04-23 12:36
Closing this since I confirmed that this is a connectivity issue.

**Closed by Thanhphan1147** 2024-04-23 12:36 UTC
